name = "bukens-api"
main = "src/index.ts"
compatibility_date = "2026-10-09"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "bukens-db"
database_id = "63631017-241c-4c27-b879-983349308fdc"
migrations_dir = "migrations"
